'use client';
import dynamic from 'next/dynamic';
import 'smart-webcomponents-react/source/styles/smart.default.css';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import { useState } from 'react';

//Dynamically import the Smart.Scheduler component
const Scheduler = dynamic(() => import('smart-webcomponents-react/scheduler'), {
  ssr: false, //no server-side rendering
  loading: () => <div>로딩중...</div>,
});

const SchdeulerComponent = () => {
  const today = new Date(),
    todayDate = today.getDate(),
    currentYear = today.getFullYear(),
    currentMonth = today.getMonth(),
    currentTime = today.getHours(),
    currentMuinute = today.getMinutes();

  const [dataSource, setDataSource] = useState([
    {
      label: 'Google AdWords Strategy',
      dateStart: new Date(currentYear, currentMonth, todayDate, 9, 0),
      dateEnd: new Date(currentYear, currentMonth, todayDate, 10, 30),
      description: 'Some description',
      backgroundColor: '#E67C73',
    },
    {
      label: 'New Brochures',
      dateStart: new Date(currentYear, currentMonth, todayDate - 1, 11, 30),
      dateEnd: new Date(currentYear, currentMonth, todayDate - 1, 14, 15),
      backgroundColor: '#8E24AA',
    },
    {
      label: 'Brochure Design Review',
      dateStart: new Date(currentYear, currentMonth, todayDate + 2, 13, 15),
      dateEnd: new Date(currentYear, currentMonth, todayDate + 2, 16, 15),
      description: 'Some description',
      backgroundColor: '#039BE5',
    },
  ]);

  const currentTimeIndicator = true,
    shadeUntilCurrentTime = true,
    view = 'day',
    views = [
      'day',
      'week',
      'month',
      'timelineDay',
      'timelineWeek',
      'timelineMonth',
    ],
    firstDayOfWeek = 1;

  const addNewTask = () => {
    // if (currentTime > 18) {
    //   alert('현재 시간 이후에는 작업을 추가할 수 없습니다.');
    //   return;
    // }
    const newTask = {
      label: 'New Task',
      dateStart: new Date(currentYear, currentMonth, todayDate, 13, 0),
      dateEnd: new Date(currentYear, currentMonth, todayDate, 21, 0),
      backgroundColor: '#E67C73',
    };
    setDataSource([...dataSource, newTask]);
  };
  console.log('currentTime', currentTime);
  console.log('currentMuinute', currentMuinute);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>일간 작업 기록</h1>
        <div>
          <p>주요 메뉴</p>
          <div className={styles.taskContainer}>
            <button className={styles.task}>일간</button>
            <button className={styles.task}>주간</button>
            <button className={styles.task}>월간</button>
            <button className={styles.task}>타임라인</button>
          </div>
        </div>
        <div className={styles.taskContainer}>
          <button className={styles.task} onClick={addNewTask}>
            양주 옥정 세로바 절단 작업
          </button>
          <button className={styles.task}>양주 옥정 가로바 절단 작업</button>
          <button className={styles.task}>양주 옥정 하부레일 절단 작업</button>
          <button className={styles.task}>용인 구성 세로바 절단 작업</button>
        </div>
        <Scheduler
          className={styles.scheduler}
          id="scheduler"
          currentTimeIndicator={currentTimeIndicator}
          shadeUntilCurrentTime={shadeUntilCurrentTime}
          dataSource={dataSource}
          view={view}
          views={views}
          firstDayOfWeek={firstDayOfWeek}
        ></Scheduler>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.htmlelements.com/react/demos/scheduler/current-time-indicator/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img
            src="https://www.htmlelements.com/wp-content/design/assets/images/logo-htmlelements.svg"
            className={styles.imgLogo}
          />
        </a>
      </footer>
    </div>
  );
};

export default SchdeulerComponent;
